use_frameworks!

platform :ios, '16.0'

target 'Crumb_Example' do
  pod 'Crumb', :path => '../'
  pod 'SnapKit'
  target 'Crumb_Tests' do
    inherit! :search_paths
    pod 'Crumb', :path => '../'

    
  end
end
