# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest 
    
    env: 
      PROJECT: Crumb.xcodeproj
      SCHEME: Crumb-Package 
      
    strategy:
      matrix: 
        - sdk: iphonesimulator 
          destination: platform=iOS Simulator,name=iPhone 14 Pro,OS=latest
        - sdk: macosx 
          destination: arch=x86_64

    steps:
      - uses: actions/checkout@v1 
      - name: Show Lists SDK & Devices 
        run: xcodebuild -showsdks; instruments -s 

      - name: Project Gen 
        run: swift package generate-xcodeproj 

      - name: Build and Test
        run: |
          set -o set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
        env:
          SDK: ${{ matrix.env.sdk }}
          DESTINATION: ${{ matrix.env.destination }}

