# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test And Lint 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependences
      run: |
        cd Example 
        pod repo update 
        pod install
      shell: bash 
    - name: Test & Lint 
      with: 
      additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
        additional_lint_params: --private

